# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-12 04:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='title',
            field=models.CharField(default=2, max_length=120),
            preserve_default=False,
        ),
    ]
